services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    container_name: geoserver
    ports:
      - "8080:8080"   # 호스트 8080 → 컨테이너 8080
    volumes:
      - ./geoserver_data:/opt/geoserver_data
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver_data
    restart: unless-stopped